### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #2: Create code of conduct file
Add a CODE_OF_CONDUCT.md file to the project

### PR DESCRIPTION
**Pull request by lazyfuhrer**
added contributing.md file

### CODE REVIEW

**Review by eduardconstantin — COMMENTED** [review]
I think this is code of conduct

**Comment by lazyfuhrer** [comment]
yes, it's the same ig

**Comment by eduardconstantin** [comment]
Change the name of the file to CODE_OF_CODUCT.md

**Comment by lazyfuhrer** [comment]
sure

**Pull request merged**
